"""remove expected_birds and adjustment

Revision ID: 076177e68804
Revises: 478b37b37935
Create Date: 2026-07-23 13:04:34.750864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076177e68804'
down_revision: Union[str, Sequence[str], None] = '478b37b37935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'adjustment')
    op.drop_column('purchases', 'expected_birds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('expected_birds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('adjustment', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
