"""Add bank_payment to Purchase and Sale

Revision ID: 108771bd836c
Revises: a5fd83877857
Create Date: 2026-08-03 11:34:26.911655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108771bd836c'
down_revision: Union[str, Sequence[str], None] = 'a5fd83877857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('bank_payment', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('bank_payment', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'bank_payment')
    op.drop_column('purchases', 'bank_payment')
    # ### end Alembic commands ###
