"""add empty_bird_weight_g to purchase and sale

Revision ID: 18b5316a08e0
Revises: d4e8b1a92c01
Create Date: 2026-08-05 11:29:08.671960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b5316a08e0'
down_revision: Union[str, Sequence[str], None] = 'd4e8b1a92c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
