"""add_weighbridge_weight_to_sales

Revision ID: 1bf32afc0d72
Revises: 794a0937ab55
Create Date: 2026-08-04 11:15:33.195165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf32afc0d72'
down_revision: Union[str, Sequence[str], None] = '794a0937ab55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('weighbridge_weight', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'weighbridge_weight')
    # ### end Alembic commands ###
