"""Add is_locked to Purchase and Sale

Revision ID: 319d92e23b2b
Revises: e87ffaceeffb
Create Date: 2026-07-25 16:55:57.194896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319d92e23b2b'
down_revision: Union[str, Sequence[str], None] = 'e87ffaceeffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.add_column('sales', sa.Column('is_locked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'is_locked')
    op.drop_column('purchases', 'is_locked')
    # ### end Alembic commands ###
