"""add is_active to parties

Revision ID: 3f360fbe558c
Revises: cb8a99f38f07
Create Date: 2026-07-24 14:42:33.835371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f360fbe558c'
down_revision: Union[str, Sequence[str], None] = 'cb8a99f38f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'is_active')
    # ### end Alembic commands ###
