"""Add item_id to Purchase and Sale, create Item model

Revision ID: 794a0937ab55
Revises: 8dbf8f6574a9
Create Date: 2026-08-04 10:58:28.601153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794a0937ab55'
down_revision: Union[str, Sequence[str], None] = '8dbf8f6574a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=True)
    op.add_column('purchases', sa.Column('item_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_purchases_item_id'), 'purchases', ['item_id'], unique=False)
    op.create_foreign_key(None, 'purchases', 'items', ['item_id'], ['id'])
    op.add_column('sales', sa.Column('item_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_sales_item_id'), 'sales', ['item_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_item_id'), table_name='sales')
    op.drop_column('sales', 'item_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_item_id'), table_name='purchases')
    op.drop_column('purchases', 'item_id')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
