"""add driver_name to sales

Revision ID: 818d5b582fdb
Revises: 446cecd99508
Create Date: 2026-07-23 12:51:37.349382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818d5b582fdb'
down_revision: Union[str, Sequence[str], None] = '446cecd99508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('driver_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'driver_name')
    # ### end Alembic commands ###
