"""Add PaymentAllocation

Revision ID: 819aa42e2a3b
Revises: 319d92e23b2b
Create Date: 2026-07-26 21:25:26.229302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819aa42e2a3b'
down_revision: Union[str, Sequence[str], None] = '319d92e23b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_allocations', sa.Column('allocated_cash', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payment_allocations', sa.Column('allocated_upi', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_constraint(op.f('payment_allocations_sale_id_fkey'), 'payment_allocations', type_='foreignkey')
    op.drop_constraint(op.f('payment_allocations_purchase_id_fkey'), 'payment_allocations', type_='foreignkey')
    op.create_foreign_key(None, 'payment_allocations', 'sales', ['sale_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'payment_allocations', 'purchases', ['purchase_id'], ['id'], ondelete='SET NULL')
    op.drop_column('payment_allocations', 'allocated_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_allocations', sa.Column('allocated_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment_allocations', type_='foreignkey')
    op.drop_constraint(None, 'payment_allocations', type_='foreignkey')
    op.create_foreign_key(op.f('payment_allocations_purchase_id_fkey'), 'payment_allocations', 'purchases', ['purchase_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('payment_allocations_sale_id_fkey'), 'payment_allocations', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    op.drop_column('payment_allocations', 'allocated_upi')
    op.drop_column('payment_allocations', 'allocated_cash')
    # ### end Alembic commands ###
