"""add_driver_model

Revision ID: 8dbf8f6574a9
Revises: c47f414886e3
Create Date: 2026-08-04 09:18:36.533023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbf8f6574a9'
down_revision: Union[str, Sequence[str], None] = 'c47f414886e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.add_column('purchases', sa.Column('driver_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_purchases_driver_id'), 'purchases', ['driver_id'], unique=False)
    op.create_foreign_key(None, 'purchases', 'drivers', ['driver_id'], ['id'])
    op.add_column('sales', sa.Column('driver_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_sales_driver_id'), 'sales', ['driver_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_driver_id'), table_name='sales')
    op.drop_column('sales', 'driver_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_driver_id'), table_name='purchases')
    op.drop_column('purchases', 'driver_id')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
