"""Add bill_number to purchases and sales

Revision ID: aa1ec8602182
Revises: 651aa870fe5d
Create Date: 2026-07-27 09:47:25.909264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1ec8602182'
down_revision: Union[str, Sequence[str], None] = '651aa870fe5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('bill_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_purchases_bill_number'), 'purchases', ['bill_number'], unique=True)
    op.add_column('sales', sa.Column('bill_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_sales_bill_number'), 'sales', ['bill_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_bill_number'), table_name='sales')
    op.drop_column('sales', 'bill_number')
    op.drop_index(op.f('ix_purchases_bill_number'), table_name='purchases')
    op.drop_column('purchases', 'bill_number')
    # ### end Alembic commands ###
