"""Add bank_amount to PaymentTransaction

Revision ID: c47f414886e3
Revises: 108771bd836c
Create Date: 2026-08-03 11:36:13.701388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47f414886e3'
down_revision: Union[str, Sequence[str], None] = '108771bd836c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('bank_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'bank_amount')
    # ### end Alembic commands ###
