"""add nickname to party

Revision ID: c52cf3256c3a
Revises: ba7b0fa5f9df
Create Date: 2026-08-01 10:19:16.743895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52cf3256c3a'
down_revision: Union[str, Sequence[str], None] = 'ba7b0fa5f9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('nickname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'nickname')
    # ### end Alembic commands ###
