"""Update expense models

Revision ID: cb8a99f38f07
Revises: f930c9e6688a
Create Date: 2026-07-24 09:50:39.897679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8a99f38f07'
down_revision: Union[str, Sequence[str], None] = 'f930c9e6688a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_categories', sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('expense_categories', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('expenses', sa.Column('spent_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('expenses', sa.Column('expense_name', sa.String(length=255), nullable=False))
    op.add_column('expenses', sa.Column('note', sa.String(length=500), nullable=True))
    op.drop_column('expenses', 'date')
    op.drop_column('expenses', 'description')
    op.drop_column('expenses', 'remarks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('expenses', 'note')
    op.drop_column('expenses', 'expense_name')
    op.drop_column('expenses', 'spent_at')
    op.drop_column('expense_categories', 'is_active')
    op.drop_column('expense_categories', 'sort_order')
    # ### end Alembic commands ###
