"""Add PaymentAllocation model

Revision ID: e87ffaceeffb
Revises: ebabf9b199c2
Create Date: 2026-07-25 16:43:44.427315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87ffaceeffb'
down_revision: Union[str, Sequence[str], None] = 'ebabf9b199c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_id', sa.Uuid(), nullable=True),
    sa.Column('sale_id', sa.Uuid(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_id'), 'payment_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_purchase_id'), 'payment_allocations', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_sale_id'), 'payment_allocations', ['sale_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_transaction_id'), 'payment_allocations', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_allocations_transaction_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_sale_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_purchase_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    # ### end Alembic commands ###
