"""add birds to sales

Revision ID: f930c9e6688a
Revises: 076177e68804
Create Date: 2026-07-23 16:55:24.624062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f930c9e6688a'
down_revision: Union[str, Sequence[str], None] = '076177e68804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('birds_per_box', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sales', sa.Column('actual_birds', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'actual_birds')
    op.drop_column('sales', 'birds_per_box')
    # ### end Alembic commands ###
